### ISSUE TITLE
Unable to Import TeamsAdaptiveMessage from Teams.py

### ISSUE THREAD

**Issue by Kasper0905** [teward/adaptivecardsng#2]
TeamsAdaptiveMessage is not able to be imported because the messages folder is missing __init__.py.

For reference: https://stackoverflow.com/questions/456481/cant-get-python-to-import-from-a-different-folder

**Comment by teward** [comment]
`messages` is a folder, but this is intentional, I did not write the `adaptivecardsng` module to have TeamsAdaptiveMessage in messages at the time of writing.

The proper way to refer to this module with an import in the interim would be similar to as follows:

```
import adaptivecardsng
# Make sure that `card` exists as a card, see examples.

teamsmsg = adaptivecardsng.messages.teams.TeamsAdaptiveMessage(card, ...)
```

This should then work until such time as I implement an import/init in the messages folder.

Yes, this is a workaround, not a solution.  I'm still hard-writing the documentation for the module so I can have better documentation for examples, etc.
